apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-microservice
  template:
    metadata:
      labels:
        app: simple-microservice
    spec:
      containers:
        - name: app
          image: ashish8728/simple-microservice
          ports:
            - containerPort: 8080
          imagePullPolicy: Always